__version__: str

def check_recipe_files_json(snapshot_json: str) -> str: ...
def format_recipe_files_json(snapshot_json: str, identity_json: str) -> str: ...
def parse_judge_definitions_json(sources_json: str) -> str: ...
def judge_definition_schema_json() -> str: ...
