__version__: str

def check_recipe_files_json(snapshot_json: str) -> str: ...
def parse_template_manifest_json(manifest_yaml: str) -> str: ...
def resolve_template_variables_json(manifest_yaml: str, supplied_json: str) -> str: ...
def render_template_json(snapshot_json: str, variables_json: str) -> str: ...
def parse_judge_definitions_json(sources_json: str) -> str: ...
def judge_definition_schema_json() -> str: ...
